algoritmo "Excercio 5"
// Função :
// Autor :
// Data : 14/01/2021
// Seção de Declarações 
var

N1, N2, Media: real

inicio
      Escreva("Digite a primeira nota: ")
      Leia(N1)
      Escreva("Digite a segunda nota: ")
      Leia(N2)
      Media <- (N1 + N2)/ 2
      Escreval("Nota 1:", N1)
      Escreval("Nota 1:", N2)
      Escreval("A media entre",N1, " e",N2, " e igual a",Media)
// Seção de Comandos 
fimalgoritmo
