algoritmo "Exercicio 3"
// Função :
// Autor :
// Data : 14/01/2021
// Seção de Declarações 
var
   salario: real
   nome: caractere
inicio
      Escreva("Digite o nome do(a) funcionario(a): ")
      Leia(nome)
      Escreva("Digite o salario do(a) funcionario(a): ")
      Leia(salario)
      Escreval("Nome do Funcionario: ",nome)
      Escreval("Salario:",salario)
      Escreval("O funcionario(a) ",nome, " tem um salario de R$",salario)
// Seção de Comandos 
fimalgoritmo
