algoritmo "Exercio 6"
// Função :
// Autor :
// Data : 14/01/2021
// Seção de Declarações 
var
   num, antecessor, sucessor: inteiro

inicio
      Escreva("Digite um numero: ")
      Leia(num)
      antecessor <- num - 1
      sucessor <- num + 1
      Escreval("O numero base e:", num)
      Escreval("O antecessor e:", antecessor)
      Escreval("O sucessor e:", sucessor)
// Seção de Comandos 
fimalgoritmo
